# Generated by Django 4.2.29 on 2026-04-10 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat_type', models.CharField(choices=[('NONE', 'None'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], default='NONE', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['start_time']},
        ),
        migrations.AddField(
            model_name='booking',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['date', 'turf'], name='booking_boo_date_a5572e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer'], name='booking_boo_custome_3fe9c1_idx'),
        ),
        migrations.AddField(
            model_name='bookinggroup',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.customer'),
        ),
        migrations.AddField(
            model_name='bookinggroup',
            name='turf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.turf'),
        ),
        migrations.AddField(
            model_name='booking',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='booking.bookinggroup'),
        ),
    ]
